#!/bin/bash

# from https://github.com/snapcore/snapcraft/blob/master/extensions/desktop/kde-neon/launcher-specific

if [[ -z "$QT_QPA_PLATFORMTHEME" ]]; then
  gtk_based_desktops=("GNOME" "X-CINNAMON" "UNITY" "MATE" "XFCE" "LXDE" "Pantheon")
  for gtk_desktop in "${gtk_based_desktops[@]}"; do
    if [[ "$XDG_CURRENT_DESKTOP" == *"$gtk_desktop"* ]]; then
      export QT_QPA_PLATFORMTHEME="gtk3"
      break
    fi
  done
fi
export QT_QPA_PLATFORMTHEME=${QT_QPA_PLATFORMTHEME:-kde}

exec "$@"
