name: anki-ppd
base: core22
version: "2.1.54"
summary: Extensible flashcard learning program.
description: |
  Anki is a program which makes remembering things easy. Because it's a lot
  more efficient than traditional study methods, you can either greatly
  decrease your time spent studying, or greatly increase the amount you learn.

  This snap ships the upstream binary releases with as few changes as possible.
  If you are looking for actual builds from source, consider the anki-woodrow snap.
  This snap is not affiliated with the upstream project in any way.

grade: stable
confinement: strict
compression: lzo

layout:
  /usr/share/qt5:
      symlink: $SNAP/usr/share/qt5

apps:
  anki:
    command: bin/anki
    command-chain:
      - bin/remember-ld-library-path
    plugs:
      - home
      - opengl
      - network
      - browser-support
      - audio-playback
      - audio-record
    environment:
      ANKI_BASE: $SNAP_USER_COMMON/anki
      QTWEBENGINE_DISABLE_SANDBOX: 1
      LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$SNAP/usr/lib/x86_64-linux-gnu/samba:$SNAP/usr/lib/x86_64-linux-gnu/blas:$SNAP/usr/lib/x86_64-linux-gnu/lapack
      PYTHONPATH: $SNAP/usr/lib/python3/dist-packages:$SNAP/lib/python3.10/site-packages
      QT_PLUGIN_PATH: $SNAP/usr/lib/x86_64-linux-gnu/qt5/plugins:$SNAP/usr/lib/x86_64-linux-gnu
      QTWEBENGINEPROCESS_PATH: $SNAP/usr/lib/x86_64-linux-gnu/qt5/libexec/QtWebEngineProcess
      DISABLE_WAYLAND: 1
    extensions:
      - gnome

parts:
  launchers:
    plugin: dump
    source: launchers/
    organize: 
      "*": bin/

  wrappers:
    plugin: dump
    source: wrappers/
    organize: 
      "*": wrappers/

  anki:
    plugin: python
    source: .
    stage-packages:
      - libnss3
      - libxcb-icccm4
      - libxcb-image0
      - libxcb-keysyms1
      - libxcb-randr0
      - libxcb-render-util0
      - libxcb-shape0
      - libxcb-xinerama0
      - libxcb-xkb1
      - libxkbcommon-x11-0
      - mpv
      - libxv1
      - samba-libs
      - python3-pyqt5
      - python3-pyqt5.qtwebengine
      - python3-pyqt5.qtwebchannel
      - python3-pyqt5.qtmultimedia
      - libqt5multimedia5-plugins
      - lame
    build-environment:
      - VIRTUAL_ENV: "$CRAFT_PART_INSTALL"
      - PATH: "$VIRTUAL_ENV/bin:$PATH"
    python-packages: 
      - aqt==${SNAPCRAFT_PROJECT_VERSION}

  cleanup:
    after: [launchers, wrappers, anki]
    plugin: nil
    override-prime: |
        set -eux
        for CRUFT in bug lintian man; do
            rm -rf $CRAFT_PRIME/usr/share/$CRUFT
        done
        find $CRAFT_PRIME/usr/share/doc/ -type f -not -name 'copyright' -delete
        find $CRAFT_PRIME/usr/share -type d -empty -delete
