name: anki-ppd
base: core20 
version: "2.1.49"
summary: Extensible flashcard learning program.
description: |
  Anki is a program which makes remembering things easy. Because it's a lot
  more efficient than traditional study methods, you can either greatly
  decrease your time spent studying, or greatly increase the amount you learn.

  This snap ships the upstream binary releases with as few changes as possible.
  If you are looking for actual builds from source, consider the anki-woodrow snap.
  This snap is not affiliated with the upstream project in any way.

grade: stable
confinement: strict
compression: lzo

layout:
  /usr/share/qt5:
      symlink: $SNAP/kf5/usr/share/qt5

apps:
  anki:
    command: bin/anki
    command-chain:
      - bin/remember-ld-library-path
    plugs:
      - home
      - opengl
      - network
      - browser-support
      - audio-playback
      - audio-record
    environment:
      ANKI_BASE: $SNAP_USER_COMMON/anki
      QTWEBENGINE_DISABLE_SANDBOX: 1
      LD_LIBRARY_PATH: $SNAP/usr/lib/x86_64-linux-gnu/samba
      PYTHONPATH: $SNAP/usr/lib/python3/dist-packages
    extensions:
      - kde-neon

package-repositories:
-   type: apt
    components:
    - main
    suites:
    - focal
    key-id: 444DABCF3667D0283F894EDDE6D4736255751E5D
    url: http://origin.archive.neon.kde.org/user
    key-server: keyserver.ubuntu.com

parts:
  launchers:
    plugin: dump
    source: launchers/
    organize: 
      "*": bin/

  wrappers:
    plugin: dump
    source: wrappers/
    organize: 
      "*": wrappers/

  anki:
    plugin: python
    stage-packages:
      - libnss3
      - libxcb-icccm4
      - libxcb-image0
      - libxcb-keysyms1
      - libxcb-randr0
      - libxcb-render-util0
      - libxcb-shape0
      - libxcb-xinerama0
      - libxcb-xkb1
      - libxkbcommon-x11-0
      - mpv
      - libxv1
      - samba-libs
      - python3-pyqt5
      - python3-pyqt5.qtwebengine
      - python3-pyqt5.qtwebchannel
    python-packages:
      - aqt==2.1.49
    prime:
      - -lib/python3.8/site-packages/PyQt*

  cleanup:
    after: [launchers, wrappers, anki]
    plugin: nil
    build-snaps: [kde-frameworks-5-qt-5-15-3-core20]
    override-prime: |
        set -eux
        for snap in "kde-frameworks-5-qt-5-15-3-core20"; do  # List all content-snaps you're using here
            cd "/snap/$snap/current" && find . -type f,l -exec rm -f "$SNAPCRAFT_PRIME/{}" "$SNAPCRAFT_PRIME/usr/{}" \;
        done
        for CRUFT in bug lintian man; do
            rm -rf $SNAPCRAFT_PRIME/usr/share/$CRUFT
        done
        find $SNAPCRAFT_PRIME/usr/share/doc/ -type f -not -name 'copyright' -delete
        find $SNAPCRAFT_PRIME/usr/share -type d -empty -delete
